kleros/kleros

contracts/KlerosPOC.sol
package.json
test/klerosPOC.js
truffle.js

Tests not passing probably due to kleros-helpers not being in npm.

Revert "Action Indicators Kleros POC"

---

contracts/KlerosPOC.sol
package.json
test/klerosPOC.js
truffle.js

Revert "Revert "Action Indicators Kleros POC""

---

contracts/KlerosPOC.sol
package.json
test/klerosPOC.js
truffle.js

Revert "Revert "Revert "Action Indicators Kleros POC"""

---

contracts/KlerosPOC.sol

- go directly to AtStake stage for a tie, not for abstaining winning

Bugfix: wrong conditions for moving directly to AtStake

---

contracts/KlerosPOCCourt.sol

Just a small change to use current Pinakion.
Fixes #34 
Also, maybe it would be a good idea to add a simple test for this contract? Just calling the constructor, making sure it builds, so it's easier to catch bugs like this in the future.

Use new Pinakion contract in KlerosPOCCourt

---

README.md

* Added "We follow [GitHub Flow](https://guides.github.com/introduction/flow/) in this repository."
* Minor rewording in contributing section

Added git workflow line

---

contracts/Kleros.sol

**Before:**
```
/** @dev Setter for rng.
*  @param _rng An instance of RNG.
*/
```
**After:**
```
/** @dev Setter for rng.
*  @param _rng An instance of RNG.
*/
```

Fixes indentation in a doxygen comment line

---

contracts/KlerosCourt.sol
contracts/POC/KlerosPOCCourt.sol

Related to #47 
Please review @clesaege  @epiqueras

Feat: Unaffordable appeal cost on KlerosPOCCourt when there is no parent court

---

package.json

truffle `4.1.12` => `4.1.13`
web3 `1.0.0-beta.22` => `1.0.0-beta.34`

[chore] update dependencies

---

auditor.md

Some notes for potential auditors of the Kleros contract

Notes for auditors added

---

.soliumignore
.soliumrc.json

Same changes as in https://github.com/kleros/kleros-interaction/pull/93

Style: Add initial config of Solium

---

package.json

Fix: Package version

---

contracts/kleros/ArbitratorCourt.sol
contracts/kleros/KlerosCourt.sol

https://github.com/kleros/kleros-interaction/issues/109

refactor: move arbitratorcourt inside kleros

---

package.json
test/kleros/kleros-liquid.js
yarn.lock

Refactor helpers so that we use from OpenZeppelin 

---

contracts/kleros/POC/KlerosPOCCourt.sol
test/kleros/POC/kleros-poc.js

- lint erros: sol and js
- import 'kleros-interaction/contracts/standard/arbitration/ArbitrableTransaction.sol'
- fix construction parameters order for all occurrences of ArbitrableTransaction

fix(kleros-poc): fixed KlerosPOC tests

---

contracts/Governance.sol
package.json
test/governance.js
yarn.lock

feat(governance): governance contract

---

contracts/Governance.sol
test/governance.js

The new state _Executed_ will be used for avoiding execution of an already executed proposal.

feat(governance): add a new ProposalState Executed

---

contracts/kleros/KlerosGovernor.sol
test/kleros/kleros-governor.js

- Add indexes on `_listID` and `_submitter`
- Capitalize event name to match other Kleros contracts

refactor(KlerosGovernor): add idxs and capitalize list submission event

---

contracts/kleros/KlerosGovernor.sol
test/kleros/kleros-governor.js

- Add `MetaEvidence` and `Dispute` event logs

feat(KlerosGovernor): add evidence standard events

---

contracts/data-structures/SortitionSumTreeFactory.sol

Minor updates to SortitionSumTreeFactory

---

contracts/kleros/KlerosLiquid.sol

Minor updates to KlerosLiquid

---

contracts/kleros/KlerosGovernor.sol

RAB Pragma & Comment Updated in KlerosGovernor

---

contracts/kleros/KlerosGovernor.sol

Specify the use of `deployer`
Add myself as reviewer

docs(KlerosGovernor.sol): Review

---

contracts/kleros/KlerosGovernor.sol
contracts/kleros/KlerosLiquid.sol

Add myself as reviewer.
KlerosGovernor: https://docs.google.com/document/d/1TjJJXvXNzhlT02oIAiMIJGMfv-QgKHL3CVmDcjbLG68/edit?usp=sharing
KlerosLiquid: https://docs.google.com/document/d/1WXPhpXo3f0qNBEuAUrYU4PqCy0Rvn3Fm7Gf631mIHYU/edit?usp=sharing

RAB review update

---

contracts/data-structures/SortitionSumTreeFactory.sol
contracts/kleros/KlerosLiquid.sol

KlerosLiquid and deps: https://docs.google.com/document/d/1vJcLtkct28UKNJi_lDCUQ93VSQ3-TdjVwCjYMblXMmo/edit#heading=h.ji0ib7j47va8

docs: Add myself to the RAB review pragma
